# Site settings
name: Thanh Vo
title: Thanh Vo | Machine Learning Engineer
description: a Machine Learning enthusiast focused on Natural Language Processing & Computer Vision
url: https://hiepthanh0510.github.io/
baseurl: ''
email: vohiepthanh510@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://hiepthanh0510.github.io/resume_Thanh.pdf
social:
  - title: twitter
    url: https://twitter.com/ref1n11349
  - title: github
    url: https://github.com/HiepThanh0510
  - title: linkedin
    url: https://www.linkedin.com/in/vohiepthanh/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
